{% set name = "bluesky-darkframes" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3207e164d15d23b0fe4712dc2d275d1f5a5802c12f46c7126ab7a2884d5f321b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - bluesky
    - event-model >=1.14.0
    - frozendict
    - numpy

test:
  requires:
    - caproto
  commands:
    - OPHYD_CONTROL_LAYER=caproto python -c 'import bluesky_darkframes'

about:
  home: https://github.com/bluesky/bluesky-darkframes
  license: BSD (3-clause)
  license_family: BSD
  license_file: LICENSE
  summary: Tools for acquiring and subtracting darkframes
  doc_url: https://blueskyproject.io/bluesky-darkframes
  dev_url: https://github.com/bluesky/bluesky-darkframes
